<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Zhanuzaks-MacBook-Pro.local" ignored="0" name="Default test" tests="1" failures="1" timestamp="11 Jul 2018 01:29:13 GMT" time="8.258" errors="0">
  <testcase name="runScenario" time="7.844" classname="cucumber.api.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="expected [https://dev.creditninja.com/loan_application/about_your_work] but found [https://qa.creditninja.com/loan_application/about_your_work]">
      <![CDATA[java.lang.AssertionError: expected [https://dev.creditninja.com/loan_application/about_your_work] but found [https://qa.creditninja.com/loan_application/about_your_work]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at pages.HomePage.urlTitleVerify(HomePage.java:113)
at step_definitions.ui.Ui_aboutYourWork_field_validation_stepDef.user_navigates_to_CreditNinja_loan_application_about_your_work_and_verify_url_and_tite_of_it(Ui_aboutYourWork_field_validation_stepDef.java:32)
at âœ½.user navigates to CreditNinja loan application about your work and verify url and tite of it(src/test/resources/testData/Ui_aboutYourWork_field_validation.feature:5)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
